"""Public storage-independent program analysis API."""

from chipchain.analysis.analyzer import ProgramAnalyzer
from chipchain.analysis.angr_analyzer import AngrAnalyzer
from chipchain.analysis.demo_analyzer import DemoAnalyzer
from chipchain.analysis.errors import (
    AnalysisIngestionError,
    InvalidAnalysisInputError,
    ProgramAnalysisError,
    UnsupportedArtifactError,
)
from chipchain.analysis.ingestion import ingest_analysis_result
from chipchain.analysis.memory_map import MemoryMap, MemoryRegion, MemoryRegionKind
from chipchain.analysis.models import ProgramAnalysisResult, ProgramArtifact
from chipchain.analysis.static_behavior_models import (
    PHASE10D_STATIC_BEHAVIOR_ANALYSIS_PROJECTION_CONTRACT,
    PHASE10D_STATIC_BEHAVIOR_GRAPH_PROJECTION_CONTRACT,
    PHASE10D_STATIC_PATTERN_BINDING_PROJECTION_CONTRACT,
    StaticAssertionClass,
    StaticBehaviorAnalysisProjection,
    StaticBehaviorGraphProjection,
    StaticBehaviorNode,
    StaticBehaviorNodeKind,
    StaticBehaviorProjectionScope,
    StaticBehaviorRelation,
    StaticBehaviorRelationKind,
    StaticPatternBindingKind,
    StaticPatternBindingProjection,
    StaticPatternBindingRecord,
    StaticPatternBindingSemantics,
    StaticPatternOrderBasis,
    StaticPatternPathWitnessUse,
    StaticObjectiveObligation,
    StaticSemanticAttributes,
    static_behavior_analysis_projection_id,
    static_behavior_graph_projection_id,
    static_behavior_node_id,
    static_behavior_relation_id,
    static_pattern_binding_projection_id,
    static_pattern_binding_record_id,
)
from chipchain.analysis.static_behavior_projection import (
    PHASE10D_A_PROFILE_STATIC_BEHAVIOR_PROJECTION_MATERIALIZATION_CONTRACT,
    AProfileStaticBehaviorProjectionMaterialization,
    a_profile_static_behavior_projection_materialization_id,
    project_static_behavior_analysis,
)

__all__ = [
    "AnalysisIngestionError",
    "AngrAnalyzer",
    "AProfileStaticBehaviorProjectionMaterialization",
    "DemoAnalyzer",
    "InvalidAnalysisInputError",
    "MemoryMap",
    "MemoryRegion",
    "MemoryRegionKind",
    "ProgramAnalysisError",
    "ProgramAnalysisResult",
    "ProgramAnalyzer",
    "ProgramArtifact",
    "PHASE10D_STATIC_BEHAVIOR_ANALYSIS_PROJECTION_CONTRACT",
    "PHASE10D_A_PROFILE_STATIC_BEHAVIOR_PROJECTION_MATERIALIZATION_CONTRACT",
    "PHASE10D_STATIC_BEHAVIOR_GRAPH_PROJECTION_CONTRACT",
    "PHASE10D_STATIC_PATTERN_BINDING_PROJECTION_CONTRACT",
    "StaticAssertionClass",
    "StaticBehaviorAnalysisProjection",
    "StaticBehaviorGraphProjection",
    "StaticBehaviorNode",
    "StaticBehaviorNodeKind",
    "StaticBehaviorProjectionScope",
    "StaticBehaviorRelation",
    "StaticBehaviorRelationKind",
    "StaticPatternBindingKind",
    "StaticPatternBindingProjection",
    "StaticPatternBindingRecord",
    "StaticPatternBindingSemantics",
    "StaticPatternOrderBasis",
    "StaticPatternPathWitnessUse",
    "StaticObjectiveObligation",
    "StaticSemanticAttributes",
    "UnsupportedArtifactError",
    "ingest_analysis_result",
    "a_profile_static_behavior_projection_materialization_id",
    "project_static_behavior_analysis",
    "static_behavior_analysis_projection_id",
    "static_behavior_graph_projection_id",
    "static_behavior_node_id",
    "static_behavior_relation_id",
    "static_pattern_binding_projection_id",
    "static_pattern_binding_record_id",
]
