"""Public storage-independent program analysis API."""

from chipchain.analysis.analyzer import ProgramAnalyzer
from chipchain.analysis.angr_analyzer import AngrAnalyzer
from chipchain.analysis.demo_analyzer import DemoAnalyzer
from chipchain.analysis.errors import (
    AArch64StaticProgramStructureBackendError,
    AArch64StaticProgramStructureExtractorError,
    AArch64StaticSemanticBackendError,
    AArch64StaticSemanticDecoderError,
    AnalysisIngestionError,
    InvalidAnalysisInputError,
    ProgramAnalysisError,
    UnsupportedArtifactError,
)
from chipchain.analysis.aarch64_static_program_structure_extractor import (
    AARCH64_STATIC_PROGRAM_STRUCTURE_EXTRACTOR_PROFILE_CFGFAST_V1,
    AngrAArch64StaticProgramStructureExtractor,
)
from chipchain.analysis.aarch64_static_semantic_decoder import (
    AARCH64_STATIC_SEMANTIC_DECODER_PROFILE_AUDITED_PARTIAL_V1,
    AngrAArch64StaticSemanticDecoder,
)
from chipchain.analysis.ingestion import ingest_analysis_result
from chipchain.analysis.memory_map import MemoryMap, MemoryRegion, MemoryRegionKind
from chipchain.analysis.models import ProgramAnalysisResult, ProgramArtifact
from chipchain.analysis.static_semantic_models import (
    PHASE10D_STATIC_SEMANTIC_INSTRUCTION_FACT_CONTRACT,
    PHASE10D_STATIC_SEMANTIC_INVENTORY_CONTRACT,
    StaticSemanticAttribute,
    StaticSemanticAttributeName,
    StaticSemanticFactScope,
    StaticSemanticInstructionFact,
    StaticSemanticInventory,
    StaticSemanticInventoryScope,
    StaticSemanticOperation,
    static_semantic_instruction_fact_id,
    static_semantic_inventory_id,
)
from chipchain.analysis.static_semantic_graph_models import (
    PHASE10D_STATIC_SEMANTIC_GRAPH_MATERIALIZATION_CONTRACT,
    PHASE10D_STATIC_SEMANTIC_GRAPH_PROJECTION_CONTRACT,
    StaticSemanticGraphNode,
    StaticSemanticGraphNodeKind,
    StaticSemanticGraphProjection,
    StaticSemanticGraphProjectionScope,
    StaticSemanticGraphRelation,
    StaticSemanticGraphRelationKind,
    static_semantic_graph_diagnostics,
    static_semantic_graph_node_id,
    static_semantic_graph_projection_id,
    static_semantic_graph_relation_id,
)
from chipchain.analysis.static_semantic_graph_projection import (
    StaticSemanticGraphProjectionMaterialization,
    project_static_semantic_inventory,
    static_semantic_graph_materialization_id,
)
from chipchain.analysis.static_program_structure_models import (
    PHASE10D_STATIC_PROGRAM_CFG_EDGE_CONTRACT,
    PHASE10D_STATIC_PROGRAM_FUNCTION_CFG_CONTRACT,
    PHASE10D_STATIC_PROGRAM_STRUCTURE_INVENTORY_CONTRACT,
    StaticProgramCfgEdge,
    StaticProgramCfgSemantics,
    StaticProgramFunctionCfg,
    StaticProgramStructureInventory,
    StaticProgramStructureInventoryScope,
    static_program_basic_block_source_id,
    static_program_cfg_edge_id,
    static_program_function_cfg_id,
    static_program_structure_diagnostics,
    static_program_structure_inventory_id,
)
from chipchain.analysis.static_behavior_models import (
    PHASE10D_STATIC_BEHAVIOR_ANALYSIS_PROJECTION_CONTRACT,
    PHASE10D_STATIC_BEHAVIOR_GRAPH_PROJECTION_CONTRACT,
    PHASE10D_STATIC_PATTERN_BINDING_PROJECTION_CONTRACT,
    StaticAssertionClass,
    StaticBehaviorAnalysisProjection,
    StaticBehaviorGraphProjection,
    StaticBehaviorNode,
    StaticBehaviorNodeKind,
    StaticBehaviorProjectionScope,
    StaticBehaviorRelation,
    StaticBehaviorRelationKind,
    StaticPatternBindingKind,
    StaticPatternBindingProjection,
    StaticPatternBindingRecord,
    StaticPatternBindingSemantics,
    StaticPatternOrderBasis,
    StaticPatternPathWitnessUse,
    StaticObjectiveObligation,
    StaticSemanticAttributes,
    static_behavior_analysis_projection_id,
    static_behavior_graph_projection_id,
    static_behavior_node_id,
    static_behavior_relation_id,
    static_pattern_binding_projection_id,
    static_pattern_binding_record_id,
)
from chipchain.analysis.static_behavior_projection import (
    PHASE10D_A_PROFILE_STATIC_BEHAVIOR_PROJECTION_MATERIALIZATION_CONTRACT,
    AProfileStaticBehaviorProjectionMaterialization,
    a_profile_static_behavior_projection_materialization_id,
    project_static_behavior_analysis,
)

__all__ = [
    "AARCH64_STATIC_PROGRAM_STRUCTURE_EXTRACTOR_PROFILE_CFGFAST_V1",
    "AARCH64_STATIC_SEMANTIC_DECODER_PROFILE_AUDITED_PARTIAL_V1",
    "AArch64StaticProgramStructureBackendError",
    "AArch64StaticProgramStructureExtractorError",
    "AArch64StaticSemanticBackendError",
    "AArch64StaticSemanticDecoderError",
    "AnalysisIngestionError",
    "AngrAnalyzer",
    "AngrAArch64StaticProgramStructureExtractor",
    "AngrAArch64StaticSemanticDecoder",
    "AProfileStaticBehaviorProjectionMaterialization",
    "DemoAnalyzer",
    "InvalidAnalysisInputError",
    "MemoryMap",
    "MemoryRegion",
    "MemoryRegionKind",
    "ProgramAnalysisError",
    "ProgramAnalysisResult",
    "ProgramAnalyzer",
    "ProgramArtifact",
    "PHASE10D_STATIC_SEMANTIC_INSTRUCTION_FACT_CONTRACT",
    "PHASE10D_STATIC_SEMANTIC_INVENTORY_CONTRACT",
    "PHASE10D_STATIC_SEMANTIC_GRAPH_MATERIALIZATION_CONTRACT",
    "PHASE10D_STATIC_SEMANTIC_GRAPH_PROJECTION_CONTRACT",
    "PHASE10D_STATIC_PROGRAM_CFG_EDGE_CONTRACT",
    "PHASE10D_STATIC_PROGRAM_FUNCTION_CFG_CONTRACT",
    "PHASE10D_STATIC_PROGRAM_STRUCTURE_INVENTORY_CONTRACT",
    "PHASE10D_STATIC_BEHAVIOR_ANALYSIS_PROJECTION_CONTRACT",
    "PHASE10D_A_PROFILE_STATIC_BEHAVIOR_PROJECTION_MATERIALIZATION_CONTRACT",
    "PHASE10D_STATIC_BEHAVIOR_GRAPH_PROJECTION_CONTRACT",
    "PHASE10D_STATIC_PATTERN_BINDING_PROJECTION_CONTRACT",
    "StaticAssertionClass",
    "StaticSemanticAttribute",
    "StaticSemanticAttributeName",
    "StaticSemanticFactScope",
    "StaticSemanticInstructionFact",
    "StaticSemanticInventory",
    "StaticSemanticInventoryScope",
    "StaticSemanticOperation",
    "StaticSemanticGraphNode",
    "StaticSemanticGraphNodeKind",
    "StaticSemanticGraphProjection",
    "StaticSemanticGraphProjectionMaterialization",
    "StaticSemanticGraphProjectionScope",
    "StaticSemanticGraphRelation",
    "StaticSemanticGraphRelationKind",
    "StaticProgramCfgEdge",
    "StaticProgramCfgSemantics",
    "StaticProgramFunctionCfg",
    "StaticProgramStructureInventory",
    "StaticProgramStructureInventoryScope",
    "StaticBehaviorAnalysisProjection",
    "StaticBehaviorGraphProjection",
    "StaticBehaviorNode",
    "StaticBehaviorNodeKind",
    "StaticBehaviorProjectionScope",
    "StaticBehaviorRelation",
    "StaticBehaviorRelationKind",
    "StaticPatternBindingKind",
    "StaticPatternBindingProjection",
    "StaticPatternBindingRecord",
    "StaticPatternBindingSemantics",
    "StaticPatternOrderBasis",
    "StaticPatternPathWitnessUse",
    "StaticObjectiveObligation",
    "StaticSemanticAttributes",
    "UnsupportedArtifactError",
    "ingest_analysis_result",
    "a_profile_static_behavior_projection_materialization_id",
    "project_static_behavior_analysis",
    "project_static_semantic_inventory",
    "static_behavior_analysis_projection_id",
    "static_behavior_graph_projection_id",
    "static_behavior_node_id",
    "static_behavior_relation_id",
    "static_pattern_binding_projection_id",
    "static_pattern_binding_record_id",
    "static_semantic_instruction_fact_id",
    "static_semantic_inventory_id",
    "static_semantic_graph_diagnostics",
    "static_semantic_graph_materialization_id",
    "static_semantic_graph_node_id",
    "static_semantic_graph_projection_id",
    "static_semantic_graph_relation_id",
    "static_program_basic_block_source_id",
    "static_program_cfg_edge_id",
    "static_program_function_cfg_id",
    "static_program_structure_diagnostics",
    "static_program_structure_inventory_id",
]
