"""Optional integration tests for the real ARM angr adapter."""

from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from pathlib import Path
from types import SimpleNamespace

import pytest

from chipchain.analysis import (
    AngrAnalyzer,
    InvalidAnalysisInputError,
    ProgramAnalysisResult,
    ProgramArtifact,
    UnsupportedArtifactError,
    ingest_analysis_result,
)
from chipchain.graph import NetworkXGraphRepository
from chipchain.models import Architecture, EvidenceType, Layer, RelationType

angr = pytest.importorskip("angr")

pytestmark = pytest.mark.angr

FIXTURE_DIRECTORY = Path(__file__).parent / "fixtures" / "angr" / "arm_call_chain"
FIXTURE_PATH = FIXTURE_DIRECTORY / "arm_call_chain.elf"


@pytest.fixture
def angr_artifact() -> ProgramArtifact:
    """Return the explicitly synthetic owned ARM ELF artifact."""

    return ProgramArtifact(
        id="synthetic-arm-call-chain",
        architecture=Architecture.ARM,
        artifact_type="elf",
        path=str(FIXTURE_PATH),
        fixture_identifier="synthetic-arm-call-chain-elf",
        metadata={"fixture": True, "synthetic": True, "owned": True},
    )


@pytest.fixture
def angr_result(angr_artifact: ProgramArtifact) -> ProgramAnalysisResult:
    """Run CFGFast once for tests that inspect the normalized result."""

    return AngrAnalyzer().analyze(angr_artifact)


def test_fixture_hash_and_ground_truth_are_auditable() -> None:
    """Committed generated bytes must match their documented digest and truth."""

    expected_digest, expected_name = (FIXTURE_DIRECTORY / "SHA256SUMS").read_text(
        encoding="ascii"
    ).split()
    truth = json.loads(
        (FIXTURE_DIRECTORY / "ground_truth.json").read_text(encoding="utf-8")
    )

    assert expected_name == FIXTURE_PATH.name
    assert hashlib.sha256(FIXTURE_PATH.read_bytes()).hexdigest() == expected_digest
    assert truth["fixture_type"] == "synthetic"
    assert truth["architecture"] == "ARM"
    assert truth["unresolved_calls"] == [
        {
            "caller": "indirect_dispatch",
            "callsite": "0x1003c",
            "instruction": "blx r3",
            "reason": "register target is intentionally unconstrained",
        }
    ]


def test_angr_project_loads_fixture_as_arm_without_libraries() -> None:
    """The environment gate uses a real Project against the owned ARM ELF."""

    project = angr.Project(str(FIXTURE_PATH), auto_load_libs=False)

    assert project.arch.name == "ARMEL"
    assert project.arch.bits == 32
    assert project.entry == 0x10028
    assert project.loader.main_object.min_addr == 0x10000
    assert project.loader.main_object.max_addr == 0x10043


def test_cfgfast_recovers_ground_truth_functions_only(
    angr_result: ProgramAnalysisResult,
) -> None:
    """Function nodes should match main-object symbols without loader stubs."""

    node_by_name = {node.name: node for node in angr_result.nodes}

    assert set(node_by_name) == {
        "driver_like_function",
        "helper_function",
        "parse_command",
        "main",
        "indirect_dispatch",
    }
    assert {node.address for node in angr_result.nodes} == {
        "0x10000",
        "0x10008",
        "0x10018",
        "0x10028",
        "0x10038",
    }
    assert all(node.metadata["symbol_backed"] is True for node in angr_result.nodes)
    assert all(node.layer is Layer.FIRMWARE for node in angr_result.nodes)
    assert angr_result.metadata["main_object_only"] is True
    assert angr_result.metadata["function_count"] == 5


def test_cfgfast_recovers_expected_calls_and_callsite_evidence(
    angr_result: ProgramAnalysisResult,
) -> None:
    """Resolved intra-object CALLS edges must carry exact static callsite evidence."""

    node_by_id = {node.id: node for node in angr_result.nodes}
    evidence_by_id = {item.id: item for item in angr_result.evidence}
    observed = set()
    for edge in angr_result.edges:
        item = evidence_by_id[edge.evidence_ids[0]]
        observed.add(
            (
                node_by_id[edge.source_id].name,
                node_by_id[edge.target_id].name,
                item.address,
                item.instruction,
            )
        )
        assert edge.relation is RelationType.CALLS
        assert edge.metadata["call_type"] == "direct"
        assert item.type is EvidenceType.STATIC_ANALYSIS
        assert item.source == "angr_analyzer"
        assert item.artifact == "synthetic-arm-call-chain"
        assert item.verified is True

    assert observed == {
        (
            "helper_function",
            "driver_like_function",
            "0x10010",
            "bl #0x10000",
        ),
        ("parse_command", "helper_function", "0x10020", "bl #0x10008"),
        ("main", "parse_command", "0x10030", "bl #0x10018"),
    }
    assert angr_result.metadata["resolved_call_count"] == 3
    assert angr_result.metadata["unresolved_calls"] == 1
    assert angr_result.metadata["excluded_external_call_count"] == 0
    assert all(
        node_by_id[edge.source_id].name != "indirect_dispatch"
        for edge in angr_result.edges
    )


def test_result_validates_and_round_trips_json(
    angr_result: ProgramAnalysisResult,
) -> None:
    """The angr adapter must use the existing strict result contract unchanged."""

    restored = ProgramAnalysisResult.model_validate_json(
        angr_result.model_dump_json()
    )

    assert restored == angr_result
    evidence_ids = {item.id for item in restored.evidence}
    assert evidence_ids
    assert all(
        set(edge.evidence_ids).issubset(evidence_ids) for edge in restored.edges
    )


def test_angr_analysis_is_deterministic(angr_artifact: ProgramArtifact) -> None:
    """Repeated analysis must preserve IDs, ordering, and serialized semantics."""

    first = AngrAnalyzer().analyze(angr_artifact)
    second = AngrAnalyzer().analyze(angr_artifact)

    assert second == first
    assert [node.id for node in first.nodes] == sorted(node.id for node in first.nodes)
    assert [edge.id for edge in first.edges] == sorted(edge.id for edge in first.edges)
    assert [item.id for item in first.evidence] == sorted(
        item.id for item in first.evidence
    )


def test_synthetic_function_name_is_stable(angr_artifact: ProgramArtifact) -> None:
    """A symbol-free recovered node gets a stable address-only name."""

    assert AngrAnalyzer.synthetic_function_name(0x1234) == "sub_00001234"
    assert AngrAnalyzer.synthetic_function_name(0x1234) == (
        AngrAnalyzer.synthetic_function_name(0x1234)
    )
    node = AngrAnalyzer()._make_function_node(
        artifact=angr_artifact,
        function=SimpleNamespace(addr=0x1234, size=8),
        symbol_name=None,
    )
    assert node.name == "sub_00001234"
    assert node.metadata["backend"] == "angr"
    assert node.metadata["symbol"] is None
    assert node.metadata["symbol_backed"] is False
    assert node.metadata["recovered"] is True


def test_result_ingests_and_supports_graph_path(
    angr_result: ProgramAnalysisResult,
) -> None:
    """Real analyzer output must reuse ingestion and GraphPath unchanged."""

    repository = NetworkXGraphRepository()
    ingest_analysis_result(angr_result, repository)

    paths = repository.find_paths(
        "synthetic-arm-call-chain:function:00010028",
        target_id="synthetic-arm-call-chain:function:00010000",
        architecture=Architecture.ARM,
        max_hops=3,
        allowed_layers={Layer.FIRMWARE},
    )

    assert len(paths) == 1
    assert paths[0].node_ids == [
        "synthetic-arm-call-chain:function:00010028",
        "synthetic-arm-call-chain:function:00010018",
        "synthetic-arm-call-chain:function:00010008",
        "synthetic-arm-call-chain:function:00010000",
    ]
    assert paths[0].hop_count == 3


@pytest.mark.parametrize("architecture", ["risc_v", "powerpc", "sparc"])
def test_non_arm_artifacts_are_rejected(
    architecture: str,
    angr_artifact: ProgramArtifact,
) -> None:
    """Phase 4 must not silently broaden beyond the ARM MVP."""

    artifact = ProgramArtifact(
        **{
            **angr_artifact.model_dump(mode="python"),
            "architecture": architecture,
        }
    )

    with pytest.raises(UnsupportedArtifactError, match="only ARM"):
        AngrAnalyzer().analyze(artifact)


def test_unsupported_format_is_rejected(angr_artifact: ProgramArtifact) -> None:
    """The MVP accepts ELF only and does not guess raw-binary load metadata."""

    artifact = ProgramArtifact(
        **{
            **angr_artifact.model_dump(mode="python"),
            "artifact_type": "raw_binary",
        }
    )

    with pytest.raises(UnsupportedArtifactError, match="raw_binary"):
        AngrAnalyzer().analyze(artifact)


def test_missing_and_invalid_elf_inputs_use_stable_errors(tmp_path: Path) -> None:
    """Filesystem and CLE failures should not leak backend exception classes."""

    missing = ProgramArtifact(
        id="missing-arm-elf",
        architecture="arm",
        artifact_type="elf",
        path=str(tmp_path / "missing.elf"),
    )
    with pytest.raises(InvalidAnalysisInputError, match="not a file"):
        AngrAnalyzer().analyze(missing)

    invalid_path = tmp_path / "invalid.elf"
    invalid_path.write_bytes(b"not an ELF")
    invalid = ProgramArtifact(
        id="invalid-arm-elf",
        architecture="arm",
        artifact_type="elf",
        path=str(invalid_path),
    )
    with pytest.raises(InvalidAnalysisInputError, match="could not load"):
        AngrAnalyzer().analyze(invalid)


def test_end_to_end_demo_reports_recovered_program_facts() -> None:
    """The runnable demo must report facts and a real recovered call path."""

    repository_root = Path(__file__).resolve().parents[1]
    completed = subprocess.run(
        [sys.executable, "examples/arm_angr_analysis_demo.py"],
        cwd=repository_root,
        check=False,
        capture_output=True,
        text=True,
    )

    assert completed.returncode == 0, completed.stderr
    assert "Artifact: synthetic-arm-call-chain" in completed.stdout
    assert "Architecture: arm" in completed.stdout
    assert "Functions recovered: 5" in completed.stdout
    assert "Calls recovered: 3" in completed.stdout
    assert "Unresolved calls: 1" in completed.stdout
    assert "Evidence count: 3" in completed.stdout
    assert "GraphPath:" in completed.stdout
    for forbidden_claim in (
        "Vulnerability Found",
        "Exploit Confirmed",
        "Hardware Weakness",
        "Privilege Escalation",
    ):
        assert forbidden_claim not in completed.stdout
