"""Closed candidate vocabulary, separate from objective evidence levels."""

from enum import StrEnum


class ObjectiveFactKind(StrEnum):
    SI_RAW_RECORD = "SI_RAW_RECORD"
    SOURCE_DECLARED_BEHAVIOR = "SOURCE_DECLARED_BEHAVIOR"
    SI_ELF_LABEL_ANCHOR = "SI_ELF_LABEL_ANCHOR"
    ELF_TRACE_ANCHOR = "ELF_TRACE_ANCHOR"
    HARDWARE_CASE_INSTRUCTION_ANCHOR = "HARDWARE_CASE_INSTRUCTION_ANCHOR"
    ISA_OBSERVATION = "ISA_OBSERVATION"
    RTL_OBSERVATION = "RTL_OBSERVATION"
    ALIGNED_PAIR = "ALIGNED_PAIR"
    FIELD_COMPARISON = "FIELD_COMPARISON"
    DIVERGENCE_OBSERVATION = "DIVERGENCE_OBSERVATION"


class CandidateStatus(StrEnum):
    HYPOTHESIS = "HYPOTHESIS"


class CandidateEpistemicStatus(StrEnum):
    OBSERVED = "OBSERVED"
    CORRELATED = "CORRELATED"
    HYPOTHESIZED = "HYPOTHESIZED"
    UNSUPPORTED = "UNSUPPORTED"


class CandidateSupportKind(StrEnum):
    CONTEXT_REFERENCES = "CONTEXT_REFERENCES"
    NO_SUPPORT = "NO_SUPPORT"


class UnresolvedConditionKind(StrEnum):
    NO_DIRECT_SI_LABEL_ANCHOR = "NO_DIRECT_SI_LABEL_ANCHOR"
    ELF_TRACE_ANCHOR_UNAVAILABLE = "ELF_TRACE_ANCHOR_UNAVAILABLE"
    NO_AUTHENTICATED_RUN_PROVENANCE = "NO_AUTHENTICATED_RUN_PROVENANCE"
    NO_AUTHENTICATED_BUILD_PROVENANCE = "NO_AUTHENTICATED_BUILD_PROVENANCE"
    HARDWARE_REVISION_UNKNOWN = "HARDWARE_REVISION_UNKNOWN"
    PROCESSORFUZZ_VERSION_UNKNOWN = "PROCESSORFUZZ_VERSION_UNKNOWN"
    ISA_MODEL_IDENTITY_UNKNOWN = "ISA_MODEL_IDENTITY_UNKNOWN"
    CLIENT_APPLICABILITY_UNKNOWN = "CLIENT_APPLICABILITY_UNKNOWN"
    CAUSALITY_UNESTABLISHED = "CAUSALITY_UNESTABLISHED"
    NECESSITY_UNESTABLISHED = "NECESSITY_UNESTABLISHED"
    SUFFICIENCY_UNESTABLISHED = "SUFFICIENCY_UNESTABLISHED"
